import { Position } from "../../utils/position";

const BASE_POSITION_X_LEFT_CORNER: number = 0;
const BASE_POSITION_Y_LEFT_CORNER: number = 0;

const BASE_POSITION_X_RIGHT_CORNER: number = 17630;
const BASE_POSITION_Y_RIGHT_CORNER: number = 9000;

const ENEMY_HIT_RANGE: number = 300;

const WIND_RANGE: number = 1280;

const LEFT_BASE_POSITION = new Position(
  BASE_POSITION_X_LEFT_CORNER,
  BASE_POSITION_Y_LEFT_CORNER
);
const RIGHT_BASE_POSITION = new Position(
  BASE_POSITION_X_RIGHT_CORNER,
  BASE_POSITION_Y_RIGHT_CORNER
);
export {
  BASE_POSITION_X_LEFT_CORNER,
  BASE_POSITION_Y_LEFT_CORNER,
  BASE_POSITION_X_RIGHT_CORNER,
  BASE_POSITION_Y_RIGHT_CORNER,
  WIND_RANGE,
  ENEMY_HIT_RANGE,
  LEFT_BASE_POSITION,
  RIGHT_BASE_POSITION,
};
