const BASE_POSITION_X_LEFT_CORNER: number = 0;
const BASE_POSITION_Y_LEFT_CORNER: number = 0;

const BASE_POSITION_X_RIGHT_CORNER: number = 17630;
const BASE_POSITION_Y_RIGHT_CORNER: number = 9000;

export {
  BASE_POSITION_X_LEFT_CORNER,
  BASE_POSITION_Y_LEFT_CORNER,
  BASE_POSITION_X_RIGHT_CORNER,
  BASE_POSITION_Y_RIGHT_CORNER,
};
