import { Position } from "../../utils/position";

const BASE_POSITION_X_LEFT_CORNER: number = 0;
const BASE_POSITION_Y_LEFT_CORNER: number = 0;

const BASE_POSITION_X_RIGHT_CORNER: number = 17630;
const BASE_POSITION_Y_RIGHT_CORNER: number = 9000;

const ENEMY_HIT_RANGE: number = 300;
const ENEMY_FOCUS_RANGE: number = 5000;

const WIND_RANGE: number = 1280;

const LEFT_BASE_POSITION = new Position(
  BASE_POSITION_X_LEFT_CORNER,
  BASE_POSITION_Y_LEFT_CORNER
);
const RIGHT_BASE_POSITION = new Position(
  BASE_POSITION_X_RIGHT_CORNER,
  BASE_POSITION_Y_RIGHT_CORNER
);

const ATTACK_MODE_TURN_TRESHOLD: number = 120;
const ENEMY_HEALTH_TRESHOLD_FOR_SHIELD: number = 14;

export {
  BASE_POSITION_X_LEFT_CORNER,
  BASE_POSITION_Y_LEFT_CORNER,
  BASE_POSITION_X_RIGHT_CORNER,
  BASE_POSITION_Y_RIGHT_CORNER,
  WIND_RANGE,
  ENEMY_HIT_RANGE,
  LEFT_BASE_POSITION,
  RIGHT_BASE_POSITION,
  ATTACK_MODE_TURN_TRESHOLD,
  ENEMY_FOCUS_RANGE,
  ENEMY_HEALTH_TRESHOLD_FOR_SHIELD,
};
