const SEED_TRESHOLD_DAY: number = 19;
const COMPLETE_TRESHOLD_DAY: number = 20;
const GROW_T1_TRESHOLD_DAY: number = 21;
const MAX_T3_TRESHOLD: number = 5;

export {
  SEED_TRESHOLD_DAY,
  GROW_T1_TRESHOLD_DAY,
  MAX_T3_TRESHOLD,
  COMPLETE_TRESHOLD_DAY,
};
